pipeline:

  dev:
    when:
      branch: dev
      event: push
    image: python:3.5
    secrets: [ ssh_key ]
    commands:
      - mkdir /home/pi/.ssh && echo "$SSH_KEY" > /home/pi/.ssh/id_rsa && chmod 0600 /home/pi/.ssh/id_rsa
      - python ci/deploy.py 

  master:
    when:
      branch: master
      event: push
    image: python:3.5
    secrets: [ ssh_key ]
    commands:
      - mkdir /home/pi/.ssh && echo "$SSH_KEY" > /home/pi/.ssh/id_rsa && chmod 0600 /home/pi/.ssh/id_rsa
      - python ci/deploy.py 

