version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv helloworld
            . helloworld/bin/activate
            python -m pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . hello/bin/activate
            python test_hello_world.py

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Fix ssh Could not resolve hostname
          command: |
            ssh-keyscan 192.168.178.46  >> ~/.ssh/known_hosts # Add live server IP to known hosts.

      - add_ssh_keys: # add private SSH key from CircleCI account based on fingerprint.
          fingerprints:
            - "a0:d1:0c:c4:98:b7:68:4c:9a:e1:7c:17:c1:8d:e3:94"

      - run:
          name: Deploy master.
          command: if [ "${CIRCLE_BRANCH}" == "master" ]; then ssh pi@192.168.178.46  'cd /var/www/repo/scripts && . deploy.sh'; else echo "Skipped"; fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master