version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv helloworld
            . helloworld/bin/activate
            python -m pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            python test_hello_world.py

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys: 
          fingerprints:
            - "ea:e5:57:46:5c:c2:8c:b4:fc:5d:68:91:e8:1b:0d:3e"
      - run:
          name: Install sshpass
          command: |
            sudo apt-get update
            sudo apt-get install sshpass -y
      - run:
          name: Fix ssh
          command: |
            ssh-keyscan -H 192.168.178.46  >> ~/.ssh/known_hosts 
      - run:
          name: Deploy master
          command: |
            sshpass -p 'mYBerryp1' ssh pi@192.168.178.46

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master