version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ea:e5:57:46:5c:c2:8c:b4:fc:5d:68:91:e8:1b:0d:3e"
      - run:
          name: Clone frontend repository
          command: >-
            GIT_SSH_COMMAND='ssh -i /home/pi/.ssh/id_rsa'
            git clone git@github.com:sememan/hello.git /home/pi/