version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv helloworld
            . helloworld/bin/activate
            python -m pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            python test_hello_world.py

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      # - add_ssh_keys: 
      #     fingerprints:
      #       - "0c:62:d1:f6:82:41:f2:64:0b:f8:d9:86:19:70:ca:1f"
      - run:
          name: Install OpenVPN
          command: |
            sudo apt-get update
            sudo apt-get install openvpn -y
      - run:
          name: Check IP before VPN connection
          command: |
            ifconfig
            route -n
            sudo netstat -anp
            cat /etc/resolv.conf
            echo "Public IP before VPN connection is $(curl checkip.amazonaws.com)"
      - run:
          name: VPN Setup
          background: true
          command: |
            # echo $VPN_CLIENT_CONFIG | base64 --decode > /tmp/config.ovpn
            # printf "$VPN_USER\n$VPN_PASSWORD" > /tmp/vpn.login
            cp /home/circleci/repo/vpn/e.semeraro@212.184.167.99.ovpn /tmp/config.ovpn
            cp /home/circleci/repo/vpn/login.txt /tmp/vpn.login
            ls -la /tmp/
            phone_home=$(netstat -an | grep ':22 .*ESTABLISHED' | head -n1 | awk '{ split($5, a, ":"); print a[1] }') echo $phone_home
            sudo openvpn --config /tmp/config.ovpn --auth-user-pass /tmp/vpn.login \
              --route $phone_home 255.255.255.255 net_gateway \
              --route 169.254.0.0 255.255.0.0 net_gateway > /tmp/openvpn.log
      - run:
          name: Wait for the connection to be established and check
          command: |
            while [ $(cat /tmp/openvpn.log|grep -c "Initialization Sequence Completed") == 0 ]; do
              echo "Attempting to connect..."
              sleep 1;
            done
            echo "VPN Connected"
            echo "Public IP is now $(curl checkip.amazonaws.com)"
      - run:
          name: Deploy master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then ssh k2@192.168.126.89 'cd /home/k2/repo && ./deploy.sh' && exit; else echo "Skipped"; fi
      - run:
          name: Disconnect from OpenVPN
          command: sudo killall openvpn || true
          when: always
          

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master


# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCygH6c5V3Cm3Dv921UBjgbaJfABNQnO6wanuMLtLBbGkSjbKQHoh5VJgt0Q1mpO8+16Tlskk4NmSUmazhEM2Xpr4J2zs4sJiUdwA7W9TlJiTsKd4GueGgjpLESutc7x2wObIkZA/ETaX+z+O3KKmkqRoB1/rNhjarBy9n/sL07qTQqHDzGAveBjsTbS3lvEYH5u8S7UtrWWc5AUvPgkBjo1SxIZFJtYheLQoSCHBCTdwMKnY3zIW5eSddWVwRFDHJBZK/jfs+lXdUkabjvMJUwnc/+lc80+3XnypJFDSnUMiLjDbzKy6saweELoiGYOI6rAJlFv1pBeh0eqQkJydtqHdjcbZbTSinA5/Bt6PWgwH8nIs9AzeiOd5VJWcMtW3czILrJDXKfAIOumvA0si2F9bbIhVPVf/SzWk67GDGks+t2vIYBoiTwQIsRsMP2Y4ETxL751pL1WGbWStAl/hiRaJGaWLOCI/fMVRsB+4M+l1ODlvdpY2PJZGC6wg3+kFEGH9vBi63hZNwmRcEqe2NO0fkehZ42tAmb8H7yi7XPMJGutbjrBF32XwaABrUn27rdkoL8/ijH9LN8NlEKiVBngWvnXBLdPT0/Nh+ok/huC0Vy6IJaAGH1jkD+wc7djju+O0AZxxz+jYwWOIynWSXk42Lz2ePc5TDP2GJR8vdKwQ==
# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcFG2sA9EiN+VTRltxAZVLJ1n42W54uG4wfOPMrEGbDwiP42UNBlDBpSqWVgOAu5sFAkRSwhuwUQa6QiJqShOq9lF6rM/KFTQBlcHqJbCvbj6/aMzcuFD2MhOQ/Ec3XuWtW715Jw62wRlDTn7un13ye5LMAbkEYsOSEpxzZgfduIBYxi54O6ZHhjYqLtVCd2wgYpRo0tZUOkzhNZBYDdFpviE0DAbp2BPT0ywk99PVNrRzDEoydTAyhSr5wKxXL1QcfBmeTaWyuPtmkJ8yNqxYhjDgVwCM0ANuQazqjwKCaUkuIoBU1IFmJC7mXcyYAKkfEfEKp+IOiBZo+p4WvgCp emanuele@elitebook
# github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
# bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
# 140.82.112.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDb5/J6WCJ/NYNVvqnBH4bXdC8wt4y6kXhXdtgJ/b1L45lTPtS4jWkO9W9LsK3rZjJth4UjknBgwRrzRGZm4JMRm/BzyIYNYiLWToxih2MOWKeGKzNCXNJoesFBhJKoBpX2QUMbZjR/N7mpM4B1OIofhQk5gxR0HXrnA8c79qaFtMAas2uJ0vq8yMOBpllWFGcvWGuUSgUdVWwSvaraE6+6MWUjlVbdkfpqgofLu4AeiIaHGylOPWAbbKWmDKln3dnEwCclRMMr5UGZVnu90U+YO9i+AID2DCZKLQ9ELCtnDRtmOAWnfqHK3wtOO+7IymYAWsLYApOIWSPqImxyxuLB

# ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
# ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
# ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
# ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
# ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==
# ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==
# ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==
# ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==
# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDK3hNkxW0MOOmfhf45zd1NLK6oWe0Y7REynEJ+6/+aGLa0HPJYhLwFYzWwVzXZpRgTibSZ5fRoeB1f56dD8bGkj8EPdD3qQkWWo4TeG9nHGelat6GpMSFu/KS4DkZByj5x9Z406Y4bvkMEg29j3g39N1YdEvsvYMZ+1VFcvzcecrPJ9fmUca60ziIoaGKD+lD8C4S+83XJydQF0S1PxTFlo9gMFoInyhUsqx+SBGF2ApA03/WtvA2tg+nMgGMl9V7/Hh81GTYXS1eTbt1jEoBOdbohNx30ZTQOLrmcn7AyWeEivOHP9p46UU+ZvIV22rn8A0n8R8zmylMLXTrl3AN1 k2@k2de-linux
