version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv helloworld
            . helloworld/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            python test_hello_world.py
      # - setup_remote_docker:
      #     docker_layer_caching: true
      # - run:
      #     name: Build and push Docker image
      #     command: |
      #       . helloworld/bin/activate
      #       pyinstaller -F hello_world.py
      #       docker build -t ariv3ra/$IMAGE_NAME:$TAG .
      #       echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      #       docker push ariv3ra/$IMAGE_NAME:$TAG
      # - run:
      #     name: Deploy app to Digital Ocean Server via Docker
      #     command: |
      #       ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"