version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            # echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            # echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv helloworld
            . helloworld/bin/activate
            pip install --no-cache-dir -r requirements.txt
            sudo apt-get install sshpass -y
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            python test_hello_world.py
      # - setup_remote_docker:
      #     docker_layer_caching: true
      # - run:
      #     name: Build and push Docker image
      #     command: |
      #       . helloworld/bin/activate
      #       pyinstaller -F hello_world.py
      #       docker build -t sememan/$IMAGE_NAME:$TAG .
      #       echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      #       docker push sememan/$IMAGE_NAME:$TAG

      - run:
          name: Deploy app to Server 
          command: |
            pip install --upgrade pip
            mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
            sshpass -p '123456' ssh k2@192.168.126.89
            # ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"